/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface UvEbookReader {
    'display': (href: string) => Promise<void>;
    'height': string;
    'load': (url: string) => Promise<void>;
    'minSpreadWidth': number;
    'resize': () => Promise<void>;
    'width': string;
  }
}

declare global {


  interface HTMLUvEbookReaderElement extends Components.UvEbookReader, HTMLStencilElement {}
  var HTMLUvEbookReaderElement: {
    prototype: HTMLUvEbookReaderElement;
    new (): HTMLUvEbookReaderElement;
  };
  interface HTMLElementTagNameMap {
    'uv-ebook-reader': HTMLUvEbookReaderElement;
  }
}

declare namespace LocalJSX {
  interface UvEbookReader {
    'height'?: string;
    'minSpreadWidth'?: number;
    'onBookReady'?: (event: CustomEvent<any>) => void;
    'onLoadedMetadata'?: (event: CustomEvent<any>) => void;
    'onLoadedNavigation'?: (event: CustomEvent<any>) => void;
    'onRenditionAttached'?: (event: CustomEvent<any>) => void;
    'width'?: string;
  }

  interface IntrinsicElements {
    'uv-ebook-reader': UvEbookReader;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'uv-ebook-reader': LocalJSX.UvEbookReader & JSXBase.HTMLAttributes<HTMLUvEbookReaderElement>;
    }
  }
}


